st:
  server:
    port: 8000
    zookeeper:
      path: /st/server/


#    dubbo 配置
dubbo:
  application:
    name: st-server
  protocol:
    name: dubbo
    port: 10000
  registry:
    address: zookeeper://39.105.196.17:2181
    
#
rocketmq:
  consumer:
    groupName: st-server-1
    namesrvAddr: localhost:9876

#
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/st?useSSL=false
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource
    
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
