st:
  server:
    port: 8000
    zookeeper:
      path: /st/server/


#    dubbo 配置
dubbo:
  application:
    name: st-server
  protocol:
    name: dubbo
    port: 10000
  registry:
    address: zookeeper://39.105.196.17:2181
    
#
rocketmq:
  consumer:
    groupName: st
    namesrvAddr: localhost:9876

