st:
  server:
    port: 8000
    zookeeper:
      path: /st/server/


#    dubbo 配置
dubbo:
  application:
    name: st-server
  protocol:
    name: dubbo
  registry:
    address: zookeeper://39.105.196.17:2181
  

