// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package com.l99.summertime.common.protocol;

public interface STRespBodyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.l99.summertime.common.protocol.STRespBody)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *消息发送时间
   * </pre>
   *
   * <code>int64 time = 1;</code>
   */
  long getTime();

  /**
   * <pre>
   *聊天类型
   * </pre>
   *
   * <code>.com.l99.summertime.common.protocol.STType type = 2;</code>
   */
  int getTypeValue();
  /**
   * <pre>
   *聊天类型
   * </pre>
   *
   * <code>.com.l99.summertime.common.protocol.STType type = 2;</code>
   */
  com.l99.summertime.common.protocol.STType getType();

  /**
   * <pre>
   *聊天内容
   * </pre>
   *
   * <code>string text = 3;</code>
   */
  java.lang.String getText();
  /**
   * <pre>
   *聊天内容
   * </pre>
   *
   * <code>string text = 3;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();

  /**
   * <pre>
   *目标组id
   * </pre>
   *
   * <code>string group = 4;</code>
   */
  java.lang.String getGroup();
  /**
   * <pre>
   *目标组id
   * </pre>
   *
   * <code>string group = 4;</code>
   */
  com.google.protobuf.ByteString
      getGroupBytes();

  /**
   * <pre>
   *发送人id，
   * </pre>
   *
   * <code>int32 fromId = 5;</code>
   */
  int getFromId();

  /**
   * <pre>
   *发送人nick
   * </pre>
   *
   * <code>string fromNick = 6;</code>
   */
  java.lang.String getFromNick();
  /**
   * <pre>
   *发送人nick
   * </pre>
   *
   * <code>string fromNick = 6;</code>
   */
  com.google.protobuf.ByteString
      getFromNickBytes();
}
